### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [SoltauFintel/blockpuzzle#10]
can the building blocks be rotated and if so how ?

**Comment by SoltauFintel** [comment]
## Rotate the game pieces

Please click the button "Drehmodus aus" (=rotating mode off). The button and the pieces will then turn green. Tapping a piece will turn it 90 degrees to the right. Then the rotation mode must be switched off again with "Drehmodus an" (turning mode on) so that a piece can be moved into the playing field.  The rotation mode button is then brown again.

brown = normal play mode
green = rotating
grey = piece cannot be played
